# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/67c6b421-af6f-4b76-b54f-1143d4fcdfde";
    fsType = "btrfs";
    options = [ 
      "compress=zstd"
      "subvol=@"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/67c6b421-af6f-4b76-b54f-1143d4fcdfde";
    fsType = "btrfs";
    options = [ 
        "compress=zstd"
        "noatime"
        "subvol=@nix"
      ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/67c6b421-af6f-4b76-b54f-1143d4fcdfde";
    fsType = "btrfs";
    options = [ 
      "noatime"
      "subvol=@swap"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/67c6b421-af6f-4b76-b54f-1143d4fcdfde";
    fsType = "btrfs";
    options = [ 
      "compress=zstd"
      "subvol=@home"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E467-7818";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
